[project]
name = "eco-evo-pop"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[tasks]
start = { cmd = "python main.py" }

[system-requirements]
cuda = "12.0"

[dependencies]
pytorch-gpu = "*"
numpy = ">=2.2.1,<3"
opensimplex = ">=0.4.5,<0.5"
matplotlib = ">=3.10.0,<4"
noise = ">=1.2.2,<2"
pygame = ">=2.6.1,<3"
