[project]
name = "eco-evo-pop"
version = "0.1.0"
description = "Add a short description here"
channels = ["pytorch", "conda-forge"]
platforms = [
    "linux-64",
] # Remove "osx-arm64" if running on a Linux machine with NVIDIA GPU

[tasks]
start = { cmd = "python main.py" }
api = { cmd = "python api.py" }
torch = { cmd = "python torch_test.py" }

[dependencies]
numpy = ">=1.26.4,<1.27"
python = "3.11"
pygame = ">=2.1.0,<3.0"
opensimplex = ">=0.4.5,<0.5"
pytorch-gpu = "*"
cuda-version = "12.4"
matplotlib = ">=3.6.0,<4.0"
noise = ">=1.2.2,<1.3"
flask = ">=3.1.0,<3.2"
flask_cors = ">=4.0.0,<4.1"

[system-requirements]
cuda = "12.4"
