[project]
name = "eco-evo-pop"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge", "pytorch"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
# start = { cmd = "python main.py" }
start = { cmd = "python main.py" }
api = { cmd = "python api.py" }
gym = { cmd = "python run_gym.py" }
test = { cmd = "python test_gym.py" }

[dependencies]
numpy = ">=1.26.4,<1.27"
python = "3.11"
pygame = ">=2.6.0,<2.7"
opensimplex = ">=0.4.5,<0.5"
pytorch = ">=2.3.1,<2.4"
matplotlib = ">=3.9.2,<3.10"
noise = ">=1.2.2,<1.3"
flask = ">=3.1.0,<3.2"
flask_cors = ">=4.0.0,<4.1"
gymnasium = ">=1.0.0,<1.1"
swig = ">=4.3.0,<4.4"
box2d-py = ">=2.3.8,<2.4"
pettingzoo = ">=1.24.3,<1.25"
stable-baselines3 = ">=2.5.0,<2.6"
